[tool.poetry]
name = "dash"
version = "0.43.0rc4"
authors = ["chris p <chris@plot.ly>"]
description = "A Python framework for building reactive web-apps Developed by Plotly."

license = 'MIT'

keywords = ["data visualization", "react", "web application", "analytics", "AI", "machine learning"]

homepage = "https://plot.ly/products/dash/"
repository = "https://github.com/plotly/dash"
documentation = "https://dash.plot.ly/"
readme = "README.md"

classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Web Environment',
    'Framework :: Flask',
    'Intended Audience :: Developers',
    'Intended Audience :: Education',
    'Intended Audience :: Financial and Insurance Industry',
    'Intended Audience :: Healthcare Industry',
    'Intended Audience :: Manufacturing',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 2',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Topic :: Database :: Front-Ends',
    'Topic :: Office/Business :: Financial :: Spreadsheet',
    'Topic :: Scientific/Engineering :: Visualization',
    'Topic :: Software Development :: Libraries :: Application Frameworks',
    'Topic :: Software Development :: Widget Sets'
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
dash-core-components = "^0.46.0"
dash-html-components = "^0.15.0"
dash-table = "^3.6.0"
flask = "^0.12.0"
flask-compress = "^1.4.0"
plotly = "^3.8.0"

[tool.poetry.dev-dependencies]
percy = "^2.0"
pytest-sugar = "^0.9.2"
pytest = "^4.4"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


